### PR TITLE
add map2, indexedMap and length

### PR DESCRIPTION
**Pull request by patrickdet**

### CODE REVIEW

**Comment by patrickdet** [comment]
`splitByLength` is kind of a special helper needed to make `map2` work. It takes a List of lengths and a List and returns a List of Lists where each List has the number of elements specified in the first List. Maybe an example helps:

```
splitByLength [2, 3, 1] ["a", "b", "c", "d", "e", "f"]

[["a", "b"], ["c", "d", "e"], ["f"]]
```

I was thinking of contributing this to `List.Extra`. Not sure if anyone else needs this.

**Comment by patrickdet** [comment]
https://github.com/elm-community/list-extra/pull/9

**Comment by tomjkidd** [comment]
I would expect map2 :: (a -> b -> result) -> Tree a -> Tree b -> Tree Result, given the state of other libraries and the mapN functions. Maybe this just needs to be named something like mapListOverTree?

**Comment by patrickdet** [comment]
yeah while writing it i thought so too. will rename it. thanks for the feedback

**Pull request merged**
