### PR TITLE
add goToNext tree movement function

### PR DESCRIPTION
**Pull request by patrickdet**

### CODE REVIEW

**Comment by tomjkidd** [comment]
In order to keep with the other navigation functions, I would expect navigation beyond the last node to return Nothing, not the the last node again. 

Is there a reason you implemented that way? A special case you are using for? If it is to be used as an iterator, returning Nothing at the end makes figuring out it is done simpler.

**Comment by patrickdet** [comment]
ahh alright that makes sense. i went with Rich Hickey's implementation of [Clojure zipper/next](https://github.com/clojure/clojure/blob/31b804223bc8f9387f5625dae870ffa9cf0281fc/src/clj/clojure/zip.clj#L230-L244) but they have a way of detecting this. So you are right. I will change the implementation to return `Nothing` when you iterate off the end

**Comment by patrickdet** [comment]
My use case and the reason I built it this way is: I am building a Filterable Table UI Component with subrows. I want to hold the arrow down key and navigate through the rows. When I reach the end I would like it the last row to stay selected. But that isn't something the Tree should have to handle but my component's logic. So I will change the behaviour. Give me a few minutes

**Comment by tomjkidd** [comment]
Ah, I too have a habit of turning to Clojure. I might look into that implementation a bit more deeply to see how it differs.

**Comment by patrickdet** [comment]
I was just glad someone else has implemented this before. I have never really written any Clojure before but that file certainly helped. There aren't many MultiwayZipper implementations to learn from besides this one.

**Comment by patrickdet** [comment]
@tomjkidd alright updated the behaviour

**Pull request merged**
